// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/AlexKostromin/microsrv/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

// GetPart provides a mock function with given fields: ctx, id
func (_m *InventoryRepository) GetPart(ctx context.Context, id string) (*model.Part, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *InventoryRepository) ListParts(ctx context.Context, filter model.PartsFilter) ([]*model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]*model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []*model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
